layout: {zmk_keyboard: corne}
layers:
  Base:
  - TAB
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - BSPC
  - {t: ESC, h: LCTRL}
  - A
  - S
  - D
  - F
  - G
  - H
  - J
  - K
  - L
  - ;
  - ''''
  - LSHFT
  - Z
  - X
  - C
  - V
  - B
  - N
  - M
  - ','
  - .
  - /
  - '-'
  - LGUI
  - Lower
  - {t: SPACE, h: Nav}
  - RET
  - Raise
  - RALT
  Lower:
  - TAB
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - '-'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ^
  - '4'
  - '5'
  - '6'
  - '='
  - {t: ▽, type: trans}
  - LSHFT
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '1'
  - '2'
  - '3'
  - \
  - '`'
  - LGUI
  - {type: held}
  - SPACE
  - RET
  - {t: ▽, type: trans}
  - RALT
  Raise:
  - {t: ▽, type: trans}
  - Sft+1
  - Sft+2
  - '{'
  - '}'
  - '|'
  - {t: ▽, type: trans}
  - '&'
  - KP MULTIPLY
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - BSPC
  - {t: ▽, type: trans}
  - '#'
  - $
  - (
  - )
  - '`'
  - '-'
  - '='
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - \
  - '`'
  - {t: ▽, type: trans}
  - '%'
  - '*'
  - '['
  - ']'
  - '~'
  - '='
  - +
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '~'
  - LGUI
  - {t: ▽, type: trans}
  - SPACE
  - RET
  - {type: held}
  - RALT
  Nav:
  - TAB
  - '!'
  - '@'
  - '#'
  - $
  - '%'
  - ^
  - '&'
  - KP MULTIPLY
  - (
  - )
  - BSPC
  - BT CLR
  - {t: BT, h: '0'}
  - {t: BT, h: '1'}
  - {t: BT, h: '3'}
  - {t: BT, h: '4'}
  - {t: ▽, type: trans}
  - LEFT ARROW
  - DOWN
  - UP ARROW
  - RIGHT
  - {t: ▽, type: trans}
  - '`'
  - LSHFT
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '&switch_tab_left'
  - '&switch_tab_right'
  - '}'
  - '|'
  - '~'
  - LGUI
  - {t: ▽, type: trans}
  - {t: SPACE, type: held}
  - RET
  - {t: ▽, type: trans}
  - RALT
